package model;
// Generated May 19, 2016 12:58:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaGastos generated by hbm2java
 */
public class CategoriaGastos  implements java.io.Serializable {


     private Integer idCategoriaGastos;
     private String descripcion;
     private Set gastoses = new HashSet(0);

    public CategoriaGastos() {
    }

	
    public CategoriaGastos(String descripcion) {
        this.descripcion = descripcion;
    }
    public CategoriaGastos(String descripcion, Set gastoses) {
       this.descripcion = descripcion;
       this.gastoses = gastoses;
    }
   
    public Integer getIdCategoriaGastos() {
        return this.idCategoriaGastos;
    }
    
    public void setIdCategoriaGastos(Integer idCategoriaGastos) {
        this.idCategoriaGastos = idCategoriaGastos;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getGastoses() {
        return this.gastoses;
    }
    
    public void setGastoses(Set gastoses) {
        this.gastoses = gastoses;
    }




}


