package model;
// Generated May 19, 2016 12:58:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private Persona persona;
     private String telefono;
     private String empresa;
     private Set nocontratos = new HashSet(0);
     private Set profesions = new HashSet(0);
     private Set ciudads = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(Persona persona, String telefono, String empresa) {
        this.persona = persona;
        this.telefono = telefono;
        this.empresa = empresa;
    }
    public Cliente(Persona persona, String telefono, String empresa, Set nocontratos, Set profesions, Set ciudads) {
       this.persona = persona;
       this.telefono = telefono;
       this.empresa = empresa;
       this.nocontratos = nocontratos;
       this.profesions = profesions;
       this.ciudads = ciudads;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public Set getNocontratos() {
        return this.nocontratos;
    }
    
    public void setNocontratos(Set nocontratos) {
        this.nocontratos = nocontratos;
    }
    public Set getProfesions() {
        return this.profesions;
    }
    
    public void setProfesions(Set profesions) {
        this.profesions = profesions;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }




}


