package model;
// Generated May 4, 2016 1:24:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private Integer idEstado;
     private String descripcion;
     private Set productos = new HashSet(0);

    public Estado(Integer idEstado) {
        this.idEstado = idEstado;
    }

    public Estado() {

    }

	
    public Estado(String descripcion) {
        this.descripcion = descripcion;
    }
    public Estado(String descripcion, Set productos) {
       this.descripcion = descripcion;
       this.productos = productos;
    }
   
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


