package model;
// Generated May 19, 2016 12:58:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * GastosDetails generated by hbm2java
 */
public class GastosDetails  implements java.io.Serializable {


     private Integer idGastosDetails;
     private Gastos gastos;
     private BigDecimal monto;
     private Date fecha;

    public GastosDetails() {
    }

    public GastosDetails(Gastos gastos, BigDecimal monto, Date fecha) {
       this.gastos = gastos;
       this.monto = monto;
       this.fecha = fecha;
    }
   
    public Integer getIdGastosDetails() {
        return this.idGastosDetails;
    }
    
    public void setIdGastosDetails(Integer idGastosDetails) {
        this.idGastosDetails = idGastosDetails;
    }
    public Gastos getGastos() {
        return this.gastos;
    }
    
    public void setGastos(Gastos gastos) {
        this.gastos = gastos;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


