package model;
// Generated May 19, 2016 12:58:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer id;
     private Estado estado;
     private String nombre;
     private String celular;
     private String cedula;
     private String apellido;
     private Set clientes = new HashSet(0);
     private Set empleados = new HashSet(0);

    public Persona() {
    }

	
    public Persona(Estado estado, String nombre, String celular, String cedula, String apellido) {
        this.estado = estado;
        this.nombre = nombre;
        this.celular = celular;
        this.cedula = cedula;
        this.apellido = apellido;
    }
    public Persona(Estado estado, String nombre, String celular, String cedula, String apellido, Set clientes, Set empleados) {
       this.estado = estado;
       this.nombre = nombre;
       this.celular = celular;
       this.cedula = cedula;
       this.apellido = apellido;
       this.clientes = clientes;
       this.empleados = empleados;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


