package model;
// Generated May 8, 2016 2:29:43 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


    private Integer idProducto;
    private Editorial editorial;
    private Estado estado;
    private String nombre;
    private int cantidad;
    private BigDecimal precio;
    private BigDecimal precioVenta;
    private Set compras = new HashSet(0);

    public Producto() {
    }


    public Producto(Editorial editorial, Estado estado, String nombre, int cantidad, BigDecimal precio, BigDecimal precioVenta) {
        this.editorial = editorial;
        this.estado = estado;
        this.nombre = nombre;
        this.cantidad = cantidad;
        this.precio = precio;
        this.precioVenta = precioVenta;
    }
    public Producto(Editorial editorial, Estado estado, String nombre, int cantidad, BigDecimal precio, BigDecimal precioVenta, Set compras) {
        this.editorial = editorial;
        this.estado = estado;
        this.nombre = nombre;
        this.cantidad = cantidad;
        this.precio = precio;
        this.precioVenta = precioVenta;
        this.compras = compras;
    }

    public Integer getIdProducto() {
        return this.idProducto;
    }

    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Editorial getEditorial() {
        return this.editorial;
    }

    public void setEditorial(Editorial editorial) {
        this.editorial = editorial;
    }
    public Estado getEstado() {
        return this.estado;
    }

    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }

    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }

    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public Set getCompras() {
        return this.compras;
    }

    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


